# Generated by Django 2.2.4 on 2019-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20190908_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_review',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
